### ISSUE TITLE
binascii.Error: Incorrect padding

### ISSUE THREAD

**Issue by jayvdb** [QueraTeam/django-qsessions#12]
This occurred when loading `/admin/` on Django 2.2.  Note I am using django-lockdown , and I have switched between Django 3.0 and 2.2 using the same sqlite db, which might have triggered this, and why it doesnt occur when I re-try it on Django 3.1.

```py
Traceback (most recent call last):
  File "django/contrib/sessions/backends/base.py", line 189, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "lockdown/middleware.py", line 73, in __call__
    response = self.process_request(request)
  File "lockdown/middleware.py", line 172, in process_request
    token = session.get(self.session_key)
  File "django/contrib/sessions/backends/base.py", line 65, in get
    return self._session.get(key, default)
  File "django/contrib/sessions/backends/base.py", line 194, in _get_session
    self._session_cache = self.load()
  File "qsessions/backends/db.py", line 25, in load
    data = super().load()
  File "django/contrib/sessions/backends/cached_db.py", line 37, in load
    data = self.decode(s.session_data)
  File "django/contrib/sessions/backends/base.py", line 100, in decode
    encoded_data = base64.b64decode(session_data.encode('ascii'))
  File "base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

```

**Comment by mjnaderi** [comment]
Hi @jayvdb 

I think this issue is related to Django, because django-qsessions does not do anything about base64 encoding.

Possibly related ticket: https://code.djangoproject.com/ticket/31592

**Comment by jayvdb** [comment]
It seems reasonable that *q*sessions would be more aggressive in deleting the stale sessions so the upstream bug doesnt prevent startup.

**Comment by mjnaderi** [comment]
In a production environment it will log-out all users of a website. Maybe sessions contain other important information.
Instead, website owner could migrate sessions manually and keep the sessions, or decide to delete them manually.

**Comment by jayvdb** [comment]
@mjnaderi , hmm, well it is usually undesirable to have Sessions contain data which can not be retrieved from other spots, and re-suming a session from before a Django version upgrade sounds like a really bad idea.  But, in an abundance of care, auto-deleting broken sessions could be a setting, and it could be pre-set to `settings.DEBUG` so devel users get the benefit immediately and ops/prod users can the safest behavour possible.

**Comment by mjnaderi** [comment]
@jayvdb Good points. But I still think this is not qsession's responsibility to delete broken sessions. qsessions aims to keep the logic and functionalities provided by Django's original session backends, and just add some specific functionalities described as its purpose (foreign key to User, storing IP and user agent). Any Django session behavior other than these remains intact.

If I understand correctly, this issue only happens when downgrading Django version, which is a rare scenario. Upgrading Django should not have any problem according to my tests and this quote from https://code.djangoproject.com/ticket/31592:

> Support for user sessions that use the old hashing algorithm remains until Django 4.0.

**Comment by jayvdb** [comment]
> But I still think this is not qsession's responsibility to delete broken sessions.

OK, no worries.
