### ISSUE TITLE
Django 5.x compatibility?

### ISSUE THREAD

**Issue by robd003** [QueraTeam/django-qsessions#22]
Has anyone tested `django-qsessions` on the current release of Django?

Is it okay if I'd make a pull request to have tests run on Django 5.0?

**Comment by mjnaderi** [comment]
A pull request to add Django 5 to test matrix and readme is welcome.

**Comment by mjnaderi** [comment]
Fixed in d6f4317fd1738b0aa6fb0b8b8b814a0101bc468a.
