### ISSUE TITLE
Django 2.2 compatibility

### ISSUE THREAD

**Issue by akx** [QueraTeam/django-qsessions#4]
Hey there,

Just wanted to let you know there are a couple compatibility issues with Qsessions and the freshly released Django 2.2. I've raised a couple of tickets over at the Django bug tracker:

* https://code.djangoproject.com/ticket/30311  
  This is fixed by PR #3.
* https://code.djangoproject.com/ticket/30312
  The workaround is to just not _replace_ `django.contrib.sessions` with `qsessions` within `INSTALLED_APPS`, but to add it instead, but as noted in the Django ticket, this will have the side effect of an unused `django_session` table being created.

**Comment by mjnaderi** [comment]
Hi @akx,

I merged PR #3. I updated tests for Django 2.2 in [django-2.2 branch](https://github.com/QueraTeam/django-qsessions/tree/django-2.2). I also added a test for system checks.

I will merge `django-2.2` and release a new version as soon as https://code.djangoproject.com/ticket/30312 is fixed.

Thanks for submitting tickets to Django bug tracker.

**Comment by mjnaderi** [comment]
Hi @akx,
Merged `django-2.2`. Thanks for your help :+1:
