### ISSUE TITLE
Provide a non-cached backend too?

### ISSUE THREAD

**Issue by willstott101** [QueraTeam/django-qsessions#5]
According to the [official Django docs](https://docs.djangoproject.com/en/2.2/topics/http/sessions/#using-cached-sessions) there is little benefit to using a cached session back-end unless you're using memcached - an unnecessary complication in many deployments.

It would be really nice for us if we could choose a single dependency for extended sessions without having to make the cached/un-cached decision at the same time. Not to mention it would make profiling the two options much much easier.

Especially as django-user-sessions has so little activity from it's maintainers. Would you consider merging a PR which adds a non-cached db back-end?

**Comment by mjnaderi** [comment]
Hi @willstott101 

That would be nice! I agree with adding `qsessions.backends.db` session backend.

**Comment by willstott101** [comment]
Ok I have created #6 for this.

**Comment by mjnaderi** [comment]
Thanks!

I merged #6 and released `v0.3.0`.
