### ISSUE TITLE
Provide a way to detected IP/user_agent changes

### ISSUE THREAD

**Issue by Aly93** [QueraTeam/django-qsessions#8]
I took a look at your code and I think that would be very useful to implement detection of IP or user agent changes during a session: this could be indicative of a session hijacking attempt.
There is something similar implemented/in your roadmap?
Thank you!

**Comment by mjnaderi** [comment]
Hi @Aly93 

When IP or user agent changes, the session instance in DB gets updated. If you want to observe those changes, you can add a Django signal for updates of Session model:

```python
from qsessions.models import Session
from django.db.models.signals import pre_save

@receiver(pre_save, sender=Session)
def session_pre_save(sender, instance, **kwargs):
    if not instance.pk:
        # A new session is being created
        return
    else:
        # An existing session is being updated
        old_instance = Session.objects.get(pk=instance.pk)
        if instance.ip != old_instance.ip:
            print("IP changed!\n"
                  "  Old: {}\n"
                  "  New: {}".format(old_instance.ip, instance.ip))
        if instance.user_agent != old_instance.user_agent:
            print("User Agent changed!\n"
                  "  Old: {}\n"
                  "  New: {}".format(old_instance.user_agent, instance.user_agent))
```

But this method has a disadvantage: It has an extra DB query for getting the old session.

A better place to check for IP/UserAgent changes is the `load` method of session backend. You can extend the session back-end and override its `load` method, then set `SESSION_ENGINE` to your extended session back-end :


```python
from qsessions import USER_AGENT_SESSION_KEY, IP_SESSION_KEY
from qsessions.backends.cached_db import SessionStore as QSessionStore
# If you want to use `db` back-end, use following import:
# from qsessions.backends.db import SessionStore as QSessionStore

class SessionStore(QSessionStore):
    def load(self):
        data = super(SessionStore, self).load()
        if data.get(USER_AGENT_SESSION_KEY) != self.user_agent:
            print("User Agent changed!\n"
                  "  Old: {}\n"
                  "  New: {}".format(data.get(USER_AGENT_SESSION_KEY), self.user_agent))
        if data.get(IP_SESSION_KEY) != self.ip:
            print("IP changed!\n"
                  "  Old: {}\n"
                  "  New: {}".format(data.get(IP_SESSION_KEY), self.ip))
        return data
```

This can also be added as a feature to `django-qsessions`. Signals about IP/UA change can be dispatched in `load` method of `qsessions.backends.common.QSessionStoreMixin`. A PR for this is welcome.
