### ISSUE TITLE
Drop drepecated ipware API

### ISSUE THREAD

**Issue by sevdog** [QueraTeam/django-qsessions#9]
`django-ipware` has just released version [`3.0.0`](https://github.com/un33k/django-ipware/blob/3.0.0/CHANGELOG.md).

In this version they have dropped some methods already _deprecated_ in version `2.x`. Among those there are both `get_real_ip` and `get_ip` which are being replaced by `get_client_ip`.

Unfotunatelly this breaks `SessionMiddleware` in this library, thus making `django.contrib.admin` checks fail with code `admin.E410`:
```
?: (admin.E410) 'django.contrib.sessions.middleware.SessionMiddleware' must be in MIDDLEWARE in order
 to use the admin application.
```

https://github.com/QueraTeam/django-qsessions/blob/5e79430bffc646acac83da0535b28f5b4cca07e0/qsessions/middleware.py#L3

It should be released a new version using the most recent API of `ipware` and pinning at least `django-ipware>=2.0.0`.

**Comment by mjnaderi** [comment]
Fixed in ae632e814bd7217af240057b3f14d7209fdd3009 and released v0.5.0. Thanks.
